---
- name: Install libselinux-python
  yum: name=libselinux-python state=installed
  when: ansible_os_family == "Redhat"

# tasks file for tomcat

#- name: Stop tomcat just in case
#  shell: 'pkill -f tomcat'
#  ignore_errors: True
#  tags:
#    - tomcat
#  when: 
#- service: name=tomcat state=stopped

- name: Create tomcat group
  group: name=tomcat state=present
  tags:
    - tomcat

- name: Download tomcat
  shell: 'wget http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version|first() }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    -O /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz creates=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz'
  register: tomcat_downloaded
  tags:
    - tomcat

- name: Extract tomcat
  shell: tar xzf /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz 
    chdir=/opt
  when: tomcat_downloaded|changed == True
  tags:
    - tomcat

- name: Create tomcat symlink
  file: path=/opt/tomcat state=link src=/opt/apache-tomcat-{{ tomcat_version }}
  when: tomcat_downloaded|changed == True
  tags:
    - tomcat

- name: Create tomcat user
  user: name=tomcat home={{ tomcat_user_home }} uid={{ tomcat_uid }} shell=/bin/sh group=tomcat state=present
  ignore_errors: True
  tags:
    - tomcat

- name: Create tomcat init script
  template: src=tomcat.sh dest=/etc/init.d/tomcat owner=root group=root mode=0766
  when: ansible_os_family == 'RedHat'
  tags:
    - tomcat

- name: Delete temporary tomcat file
  file: path=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz state=absent
  ignore_errors: yes
  tags:
    - tomcat

- name: Set tomcat file permissions
  file: path=/opt/apache-tomcat-{{ tomcat_version }} owner={{ tomcat_user }}
    group=tomcat recurse=yes
  tags:
    - tomcat

- name: Configure Tomcat server
  template: src=server.xml.{{ tomcat_version|first() }} dest={{ catalina_home }}/conf/server.xml backup=yes
  tags:
    - tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest={{ catalina_home }}/conf/
  tags:
    - tomcat

- name: Start tomcat service
  shell: /etc/init.d/tomcat start
  tags:
    - tomcat
    
- name: wait for tomcat to start
  wait_for: port={{ http_port }} timeout=60
  tags:
    - tomcat
