---
# vars file for tomcat

# Install variables
# Make sure your versions are compatible http://tomcat.apache.org/whichversion.html
tomcat_version: '7.0.59' #7.0.59 latest 7.X release, 6.0.43 latest 6.x release
openjdk: False # Set to true to use openjdk instead of oracle java
http_port: 8080
https_port: 8443

# Environment variables
java_home: /usr/share/java/jdk8u65/ # Use when installing jdk
catalina_base: /opt/apache-tomcat-{{ tomcat_version }}
catalina_home: /opt/apache-tomcat-{{ tomcat_version }}
catalina_tempdir: /opt/apache-tomcat-{{ tomcat_version }}/temp

# User management
tomcat_user: tomcat
tomcat_user_home: /opt/{{ catalina_home }}/tmp
tomcat_uid: '500'
manager_user: manager-gui
manager_password: managersecret
