---
## ansible-playbook -i <INVETORY-FILE> -u <User> --extra-vars "hosts=AHK-INT nginx_install=true" redis_install.yml -kK
- hosts:
  - '{{ hosts }}'

  vars:
    nginx_install: true
  
  become: true

#Pre Deployment Task to validate of required details are available
  pre_tasks:
    - name: Fail if no host are provided
      fail: msg="You must supply Required host or host_group for Deployment as -e hosts=XXXX"
      when: hosts is not defined

#Invoking Redis Installation Role
  roles:
    - { role: nginx_install, when: nginx_server.role }

