---
## ansible-playbook -i <INVETORY-FILE> -u <User> --extra-vars "hosts=AHK-INT nginx_install=true" redis_install.yml -kK
- hosts: nginx
  roles:
    - role: ../roles/nginx
      nginx_sites:
        pizzamania:
          template: pizzamania.conf.j2
          server_name: pizzamania.demo.com

