---
#Title: Ansible code to provision a ec-2 instance and install MariaDB on it.
#Author: Kumar Shantanu
#description:
#company: Pizzamania Services Pvt Ltd.
#Email: km.shantanu@gmail.com
  - name: Provision MariaDB EC2 node
    hosts: local
    connection: local
    gather_facts: True
    tags: provisioning
    vars_files: 
      - group_vars/all.yml
    tasks:

#Creating Nginx machine
      - name: Creating MariaDB Instance
        local_action: ec2 
                      instance_tags="Name=MariaDB" 
                      group={{ security_group }} 
                      instance_type={{ mariadb_instance_type}} 
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
        register: ec2
      - name: Adding MariaDB ec2 dns to variable
        lineinfile: "dest=group_vars/vars.yml
                      regexp='mariadb_ec2_dns' 'line=mariadb_ec2_dns: {{ item.public_dns_name }}'
                      state=present"
        with_items: "ec2.instances"

      - name: Add instance to local host group
        add_host: name={{ item.public_dns_name }} 
                  groups=mariadb ansible_sudo=1
                  ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem
        with_items: "ec2.instances"
      - name: Wait for SSH to come up
        local_action: wait_for host={{ item.public_dns_name }}
                      port=22 
                      delay=60 
                      timeout=320
                      state=started
        with_items: "ec2.instances"

  - name: roles for mariadb machine
    hosts: mariadb
    sudo: 1
    remote_user: ec2-user
    gather_facts: True
    roles:
      - common
      - mariadb
